name: Verleng zoekertjes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run
        env:
          TWEEDEHANDS_USER: ${{ secrets.TWEEDEHANDS_USER }}
          TWEEDEHANDS_PASS: ${{ secrets.TWEEDEHANDS_PASS }}
        run: "deno run start"

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          path: screenshot.png
          name: Screenshot
          if-no-files-found: 'ignore'
